volumes:
  wordpress:
    driver_opts:
      type: none
      device: /home/yoamzil/data/wordpress
      o: bind
  mariadb:
    driver_opts:
      type: none
      device: /home/yoamzil/data/mariadb
      o: bind

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress:/var/www/html

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

networks:
  inception:
    driver: bridge
