services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb

  