services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge